label: "griko best setup 1"
description: "temp = 1"

use_dropout: True
rnn_input_dropout: 0.5
initial_state_dropout: 0.5
cell_size: 12
attn_size: 12
embedding_size: 12
bidir: True
layers: 1
use_lstm: True
steps_per_checkpoint: 10000
steps_per_eval: 10000
max_steps: 150000
optimizer: adam  
max_len: 128
batch_size: 32

data_dir: ../SLTU_griko/models/grapheme/random_split/files/
model_dir: ../SLTU_griko/models/grapheme/random_split/rand1/model/
log_file: log_griko.txt 

train_prefix: train.rand1
dev_prefix: [dev.rand1, train.rand1]
vocab_prefix: vocab.rand1

attention_type: global
attn_temperature: 1
score_function: corpus_bleu

encoders:
  - name: it

decoders:
  - name: gr
