k a n è n a s t o t e l è f o n o t è l i n a t s è r i à t t i n A n n a
e s ì ì s e s t a f a m è n a m a i i l p a s t i c c i ò t t o
a n ì c h e n d i s ò n t a o a d e r f ò m m u o n ì c h a p à r o n t a m a m è n a
e n è c h e t e f a m è n a m à i è n a n r ù s t i k o
t o s ò z o s p i c c è t s i t s è k à m i
t o c h r ò n o k a m b è n n i t i n a d r e f f ì m m u è n a è n a s t u d i è t s i m e d i c ì n a
t è l u n e v o t i m m è n e
a m e s t i p à s t a ì c h e t e l ì s o n t a à l a t ù c h a v à l o n t a
a n ì c h a n d ì s o n t a i k i a t è r a i n ì c h a p à r o n t a s t i n a g l i s ì a
e n è c h i n a f à i
p r ì m a n a p à i s t i s k ò l a
o t ì c h o t è l i è n a n j a l ì
a l l ò r a e v ò à r t e n a s t e s t u d i è o t s e m a è s t r a m a è c h o m i a a d e r f ì a d e r f ì m m u s t u d i è i f è t o p ò r k e t e j a m è d i k o
k a n o n ì s e t e k o l à d r o k e o l à d r o e m b ì k e a p ò t t u k a è c h i t a s i m à d i a
a n è r k e s e k u à i s à m b a s u v o r à z o o t s o m ì
i m à n a m u i p u l ì z z e t o s p ì t i k à i m è r i
e d e r f ì m m u e n è e r t o m è n a m à i e t t ù k ù n d u m è n a
e n e t s è r o t i g r à f i
s u l è o è n a p r à m a p e r ò m i m i l ì s i t s ì t t a p r à m a t a m i M a r ì a
ì r t e g r a m m è n o
e M à r i k a e n è f a m è n a m a i a r ù s t i k o
è r k u t t e n d i m è n i à t t u s g e n i t ò r u
è p e r i k u l ò s o n a n a t è t s i a t s è n ì t t a
M a r ì k a e s ù è f e
j a t ì ì c h e p o l e m ì s o n t a ò l i t i n a d d o m à d a
e v ò o s p ì t i o s ò z o p u l i z z è t s i k u à i s à m b a e m à n a m u t o p u l ì z z e q u à i m è r i j a t ì t ù s o z e ì c h e i p o s s i b i l i t à n o k u t è t s i q u à i m è r i
a n k ò r a e n e n d ì s i m o
o k r a s ì k a l ò e n a è n e a n v e k k i à t o
e s ù p ò s e b o t t ì g l i e ì s e g l a m m è n a d è k a
s ì m m e r i e v ò e n è c h o t i k à m i
ì s e s t a m a r à t a
f ò r s i e g g u ì k a n e
e n è c h o t i k à i
