ste ce plònni sto gràtti
en ìche na stasì
e\' se allimonùme mài
a traùdia gràfutte tse nìtta
sto tìcho tèli o jelì
è\' na ène àspro
en espìccetsa o sòzo spiccètsi tse gràtsi
pùru ka se torò mìa forà en se scerrèo mài
en ìssere pu na stasì
ta koràsia tèlone kanonimmèna
na màti èna pràma na studiètsi èna pràma
ìsose èmbi àtti finèstra
tèli àspro
o tìcho tèli nan ghialì
èchete maràta ta làchana
klèete
ton ìkusa ka ìrte
su lèo èna pràma però mi milìsi ts\' ìtta pràmata mi\' Marìa
kanonònta ta sìnnefa noò ka vrèchi
o chròno ka mbènni è\' na fào poddhà glicèa
è\' na guìkane
tin adreffì- mmu ankòra en ìrte ettù
tùo o frabbikèssano mastòri ka ìane e frabbikatòri
èchi già famèna
mì me mìni ka en èrkome
en etsèro ti gràfi
è\' na statùne ankòra atsùnniti
esù pòse bottìglie ìse glammèna dèka
evò en essèro ti e\' na gràsso
ankòra en endìsimo
è\' na stasùn ankòra atsùnniti ka èchi o lùstro anammèno
adreffì- mmu fùe pp\' òrkete etèli na diventèssi messèra
sìmmeri evò en ècho ti kàmi
