a l l ò r a f è t i p ò r k e t e è r k o m e m a p à l e e t t ù c e t r ò o p o d d ù p a s t i c c i ò t t u 
a n ì c h a n d ì s o n t a i k i a t è r a i n ì c h a p à r o n t a s t i n a g l i s ì a 
s e t i p à s t a ì t e l e à l a t o n ì c h a v à l o n t a 
t a k o r à s i a t è l o n e k a n o n i m m è n a 
t a p e t ì a e n i n d ì n n o t t e m a n e c h à t u 
è n a a f o r à s o t o t s o m ì p à s s i n i m è r a 
o c h r ò n o k a m b è n n i è n a f à o p o d d h à g l i c è a 
e j i n è k a p u l i z z è i o s p ì t i o à n t r e p o d è g g h e 
t è l u n e v o t i m m è n e 
o l à d r o ì s o z e è m b i a p ò t t u 
è r k u t t e n d i m è n i à t t u s g e n i t ò r u 
a n ì c h e n d i s ò n t a o a d e r f ò m m u o n ì c h a p à r o n t a m a m è n a 
o l ì k o e n p r a t ì m à i n e m m è n o m i n a l i p ù n a 
e v ò e n ì m e a n k ò r a p r ò n t a n g h ì z i n a r t i s t e s e t t ò 
n a m i t u s m ì n o m e 
e t è l i f a m o n o f a m è n o o l i m i a f o r à 
è r k e t e f a b b r i k à t o 
e t t è d e c i d è t s a m o k a s ì m m e r i p à m e s t i s p i à g g i a 
e M à r i k a e n è f a m è n a m a i a r ù s t i k o 
t o n ì k u s a m ò t t e è r k a t o 
e n è n a l l i m o n ì s u m e m a i t u s t a c i ù r i a m a t e s m à n e 
ì m e s t a m m è n a p à n t a t e c h ù d d h i 
a l l ò r a e v ò à r t e n a s t e s t u d i è o t s e m a è s t r a m a è c h o m i a a d e r f ì a d e r f ì m m u s t u d i è i f è t o p ò r k e t e j a m è d i k o 
p u s s è n a f a m ò s o p o è t a 
t è l i à s p r o 
è n a v o r à s o o t s o m ì k u à i k u à i m è r i 
ì o n e p o d d h ì s t r à k k o 
t ù t t o t r a v ù d i e e t o n è g r a t s e è n a p o è t a 
s t e p l ò n n i 
k a n o n ò n t a t a s ì n n e f a n o ò k a v r è c h i 
o à b b i t o u k o r a s ì u t è l i à s p r o 
t o n ì k u s a k a ì r t e 
ì c h a n a v o r à s o t o t s o m ì k à i m è r i 
