s i k u r a m è n t e s t è o n e a n k ò r a a t s ù n n i t i 
m ò t t e j è n o m e v è k k i o p u l ò t o s p ì t i m u c e p à o s t i t à l a s s a n a z ì s o 
i s o t r a ù d i è n g r a m m è n o p u s s è n a p o è t a d i k ò m m a 
ì s e s t a m a r à t a 
c i ù m è s a è n a v à l i è n a t a p p è t o 
s e t i p à s t a ì t e l e à l a t o n ì c h a v à l o n t a 
j a t ì ì c h e p o l e m ì s o n t a ò l i t i n a d d o m à d a 
a p e t à c i a k è c c i a f o r à e n d ì n n o t t e p ù r u m a n e c h à t u 
a n è r t i s t e s e t t à e v ò s t e m a r è o 
s ì m b e r i d e c i d è s s a m o n a p à m e s t i t à l a s s a s t i s p i à g g i a e p ì r t a t o ò l i s o l a m è n t e o a d r e f f ò m m u n d è 
a p e t à c i a k è c c i a u s e n d ì n n u n e i g e n i t ò r i 
m ì m e m ì n e k a e n è r k u m e 
o t ì c h o t è l i n a n g h i a l ì 
z ì s o n t a e k i a t è r a m u i n ì c h a p à r o n t a s t i n a g l i s ì a 
p ù r u k a s ì t a m i a f o r à s o l a m è n t e e s a l l i m o n ò m à i 
e s ù t a m à r e t s e t a l à c h a n a 
è g r a t s a è n a n g r à m m a a d r e f ù m m u 
o à b b e t o u k o r a s ì u è n a n e à s p r o 
i p à o n d i m è n o 
è v a l a è n a n j a l ì s t o t ì c h o 
a n ì c h e n d i s ò n t a o a d e r f ò m m u o n ì c h a p à r o n t a m a m è n a 
i m a r è t s a t o l a l à c h a n a 
e d i k ì m m u e m à n a m u o c i ù r i m u e m à n a m u c e o c i ù r i m u e h e n è c h u n e s t a m m è n a m a i s t i n G r è c i a 
m ò t t i ì r t e è t t a s e o G i u v à n n i e A n n a a n k ò r a ì c h e n a m a r è s s i 
e t t è d e c i d è t s a m o k a s ì m m e r i p à m e s t i s p i à g g i a 
t ù o o f r a b b i k è s s a n o m a s t ò r i k a ì a n e e f r a b b i k a t ò r i 
a n è r t i s e s e t t à a n d e m i n d è l a p l è o k a e m è c h i 
ì m e n d i m è n i 
a n k ò r a s t e m a r è o c e e n ì n e p r ò n t o 
o s ò z o s p i c c è t s i à t s e g r à t s i 
i A n n a à r t e n a s t è i i t t u m b r ò s e m è n a s t e p l ò n n i 
o l à d r o ì s o z e è m b i a p ò t t u 
e n ì m e a n k ò r a e n d i m è n i 
