i m à k i n a t è l i s t i a m m è n i à t t o m e k k à n i k o 
t a p e t ì a e n i n d ì n n o t t e m a n e c h à t u 
a n e v ò ì c h a d ò n t a s ì n d e k a ì c h a a n o ì s o n t a k a ì c h e n a v r è t s i 
è p e r i k o l ò s o n a n a r è t s i à t s e n ì t t a 
k a ì s s e r e k a e s ò z i k à i o b à g n o 
k a i p u l ì t s o m ì k a l ò 
t o c h r ò n o k a m b è n n i t i n a d r e f f ì m m u è n a è n a s t u d i è t s i m e d i c ì n a 
o m a r ì o t è l i f a m è n o a p p è n a o m a r è i k a è p l è o s a p o r ì t o 
n d i t ò n t a 
s t i p à s t a t è l i à l a 
e m a r è s s a t o t a l à c h a n a 
s t e c e p l ò n n i s t o g r à t t i 
c ì n o ì t s e r e k a s ì m m e r i è f r ì s k o è t s i c h r ò c e e n è k a n n e o b à g n o 
e m ì d e c i d è t s a m o k a s ì m m e r i ì c h a m o n a p à m e s t i s p i à g g i a m o n a d e r f ò m u p e r ò c ì n o ì t s e r e k a k à n n i f i à k k a c e e n ì r t e m a m a e c ì k a e t à l a s s a e p i a c e i d ò p u è t s i c h r ò 
s t è i k a s i m m è n i s t o n g h i a r d ì n o 
a n è r t i n è s s u m u k u à i s à m b a v ò r a s o t s o m ì n a f è r i 
s ò z i m i n o m i l ì s i a t ù t t o p r à m m a m e t i n A n n a 
a n è r k e s e k u à i s à m b a s u v o r à z o o t s o m ì 
a n è r t i s e s e t t à a n d e m i n d è l a p l è o k a e m è c h i 
e t è l i f a m o n o f a m è n o o l i m i a f o r à 
m ò t t i è t t a s e o G i o v à n n i e A n n a ì s t i g g h e c è p l o n n e 
k a n o n ì s o n t a t e s m à n t e ì t s e r e k a n a v r è t s i 
o l ì k o e n p r a t ì m à i n e m m è n o m i n a l i p ù n a 
e j i n è k a t è l i n a p u l i z z è s s i o s p i t i k u à i m è r i n a s t a s ì p u l i t a 
m a r è t s a t o t a l à c h a n a 
o c i ù r i m m u è p o l e m i m m è n a p à n t a 
ì t e l a è n a b a r m è n a f ù r n o n a k à n i k a l ò r ù s t i k u 
è n a s t a s ù n e a n k ò r a o r t ì 
t a p e d ì a m i n c i à è r k u t t e n d i m è n i à t t o n c i ù r i c e à t t i m à n a 
t o n ì k u s a k a ì r t e 
è g r a t s a è n a n g r à m m a a d r e f ù m m u 
o m e s s è r e m u p e k a e n è n a f à o g l i c è a j a m u k à n n o n e d à n n o i s e m è n a m u p i a c è o n e c e t a t r ò o 
ì s o z e è m b i 
