i màna- mu ipulìzze to spìti kài mèri
emarèssato ta làchana
on ìkusa na\' rti
sàtte o Giovànni èstase èstase sto spìti o èssu ankòra ce pu màregghe
o chròno ka mbènni è\' na fào poddhà glicèa
kanonìsete k o làdro ke o làdro embìke apò ttu ka èchi ta simàdia
ce fòrsi è\' na mbìke àtti finèstra o làdro
ècho ti kài
àttus genitòru
o krasì kalò e\' na ène anvekkiàto
o tìcho tèli ènan jalì
tèli tèli famèno tremmò
fòrsi stèone ankòra atsùnniti
è\' na stasùne ankòra ortì
eglàsti e còppa
tùo o frabbikèssano mastòri ka ìane e frabbikatòri
i màna ce o ciùri en è en è no scerrètsoma mài jatì ma dòkane i zoì ce agàpi
pùru ka se torò mìa forà en se scerrèo mài
tùso travùdi ìrte grammèno poddhù chrònu ampì atto poèta dikò- mma
ìme stammèna pànta techùddhi
cìo ìssere ka sìmberi kànni ssìchra ce e\' tèlise na rti
ta pedìa mincià èrkutte ndimèni àtton ciùri ce àtti màna
en ìme ankòra endimèni
an ìche ndisònta o atreffò- mmu on ìcha pàronta me mea
a me sti\' pàsta ìche telìsonta àla t\' ùcha vàlonta
mì\' me mìni en èrkome
e jinèka ène kapàce na pulizzèssi è\' na pulizzèssi o spìti ka mèri
o apesammèno o klèone o klèone òli i familiàri
pistèo ka stèone ankòra atsùnniti
marètsato ta làchana
cìni en èrkotte e\' tus mènome tròme
ègratsa ènan gràmma adrefù- mmu
ettù sto spìti èchi o lùstro anammèno signifikèi ka ankòra stèone tsùnniti en ì plomèno
