ta travùdia plèon òrria èrkutte grammèna si nìtta
eglàsti e còppa
ìtela èna bar m\' èna fùrno na kàni kalò rùstiku
u genitòru en è\' nus scerrètsume mài
evò sto derfò- mu en tu tò grazza mài ènan gràmma u derfù- mmu
i pàsta tèli àla
ste ankòra marèonta
è\' na aforàso to tsomì pàssin imèra
e\' se allimonùme mài
dòpo Giovànni jùrise o vrài èssu ìbbie poddhì stràkko jatì ìche polemìsonta òli tin addomà
an èrti ses ettà an de\' min dèla plèo ka e\' m\' èchi
evò sti\' zoì- mmu ìme pànta polemimmèna
ste kammèni sto\' giardìno sto\' cìpo
evò en ècho ti è\' na fào
en è\' na tus mìnome
Marìka esù èfe
ifènete ka o làdro mbìke apò ttu
èstasa
mòtte jènnome vèkkia pulò to spìti a pu Trièste ce èrkome ittù na zìso si tàlassa
o làdro ìsoze èmbi apò ttu
an èrtin èssu- mu kuài sàmba vòraso tsomì na fèri
ìrte grammèno
i pàsta ìtele àla
mòtti ìrte èttase o Giuvànni e Anna ankòra ìche na marèssi
i màna- mu ipulìzze to spìti kài mèri
mu bristì o dàttilo
ìcha na voràso to tsomì kài mèri
e màkina tèli stiammèni atto\' mekkàniko
kanonònta ta sìnnefa noò ka vrèchi
imarètsato la làchana
o tìcho tèli ènan jalì
jatì ìche polemìsonta poddhì
ta petìa e\' sòzune fài to gelàto prìma ka na fàne
