i s ò z i k a ì n e a n k ò r a a t s ù n n i t i 
e v ò o s p ì t i o s ò z o p u l i z z è t s i k u à i s à m b a e m à n a m u t o p u l ì z z e q u à i m è r i j a t ì t ù s o z e ì c h e i p o s s i b i l i t à n o k u t è t s i q u à i m è r i 
e n è n a f à i t o v r à i 
a k à j o t r a ù d i a a s ò z i g r à t s i i n ì t t a 
i A n n a à r t e n a s t è i i t t u m b r ò s e m è n a s t e p l ò n n i 
a l l ò r a f è t i p ò r k e t e è r k o m e m a p à l e e t t ù c e t r ò o p o d d ù p a s t i c c i ò t t u 
k a n o n ò n t a t e s m à n t e a n o ò k a v r è c h i 
n d ì s o n t a o n a d e r f ò m m u o n ì c h a p à r o n t a d e f ò r e m a m è n a 
t a p e t ì a e n i n d ì n n o t t e m a n e c h à t u 
t o f à i e e t è l i f a m è n o s ù b i t o è p r è s t o 
e n ì c h e n a s t a s ì 
s t e a n k ò r a m a r è o n t a 
e d i k ì m m u e m à n a m u o c i ù r i m u e m à n a m u c e o c i ù r i m u e h e n è c h u n e s t a m m è n a m a i s t i n G r è c i a 
o l à d r o ì s o z e è m b i a p ò t t u 
c ì n i e n è r k o t t e e t u s m è n o m e t r ò m e 
e v ò s t i z o ì m m u ì m e p à n t a p o l e m i m m è n a 
t o n ì k u s a k a ì r t e 
e n è c h i n a f à i 
i p à o v r ì s k o n t a n a f u r n o k a k à n n i t o t s o m ì k a l ò c e e n i t s è r o p u s t è i 
o l ì k o e n p r a t ì m à i n e m m è n o m i n a l i p ù n a 
i f è n e t e k a o l à d r o m b ì k e a p ò t t u 
a n è r t i n è s s u m u k u à i s à m b a v ò r a s o t s o m ì n a f è r i 
e s t è o s t o t e l è f o n o e a d r e f f ì m m u e t i n è c h i e s t è c e p l ò n n i 
n a m i t u s m ì n o m e 
e v ò e n e s s è r o t i e n a g r à s s o 
k a n o n ì s o n t a t e s m à n t e ì t s e r e k a n a v r è t s i 
s i k u r a m è n t e s t è o n e a n k ò r a a t s ù n n i t i 
e m a r a n g i à n e e t è l u n v o t i m m è n e 
k a ì s s e r e k a e s ò z i k à i o b à g n o 
c ì s i f a m ì g l i a e n è c h i n a f à i 
c ì n o ì t s e r e k a s ì m m e r i è f r ì s k o è t s i c h r ò c e e n è k a n n e o b à g n o 
a m e s t i p à s t a ì c h e t e l ì s o n t a à l a t ù c h a v à l o n t a 
a n ì c h a t o r ì s o n t a o c e r ò ì c h a t o r ì s o n t a t a s ì n n e f a c e e n ì c h a è g g u o n t a n a m e g r à n i 
