isòzi mi\' milìsi atsè tùo me tin Anna
e Marìa però stèi àrtena stèi kammèni sto\' cìpo ce e\' sòzzi rispondètsi sto telèfono e\' sòzzi milìsi sto telèfono
è\' na mbìke apò ttu
i marangiàne itèlune votimmène
an ìche torìsonta ta sìnnefa tes mànte ìche anoìsonta ka ìche na vrètsi
itèli na pài Luppìu na
mòtte jènome vèkkio pulò to spìti- mu ce pào sti\' tàlassa na zìso
o làdro imbìke apò ttu
itèlo ka i Marìa na\' rti àvvri
en ècho ti kàmi
àrte spìccetsa tse gràtsi
mòtti èttase o Giovànni e Anna ìstigghe c èplonne
i aderfì- mmu fèti p òrkete e\' na studiètsi ja mèdiko
o messère mu\' pe ka en è\' na fào glicèa ja mu kànnone dànno is emèna mu piacèone ce ta tròo
kanonìsete k o làdro ke o làdro embìke apò ttu ka èchi ta simàdia
evò en ìme ankòra prònta nghìzi na rti stes ettò
mòtti ìrte o Giovànni e Anna già ìche plòsonta
en ècho ti kài
etèli klammèno
an ìche ndisònta o atreffò- mmu on ìcha pàronta me mea
mì\' me mìni en èrkome
ta petìa en indìnnotte manechà- tu
ta travùdia plèon òrria èrkutte grammèna si nìtta
adreffì- mmu fùe pp\' òrkete etèli na diventèssi messèra
en ècho ti è\' na fào
en ìche na stasì
è\' na ène àspro
o àbbeto àtto koràsi koràsi sichiamalasposa ee ee etèli àspro
en èchete famèna mài ènan rùstiko
èrkutte ndimèna
ìtsere ka kànni tsìchra ce en ìche na natètsi
cìtto tìcho tèli ènan jalì
Marìka esù èfe
