M a r ì k a è n a r m a s t ì à v v r i 
à r t e n a i v ò s t e s t u d i è o n a n a m à s o n a d i v e n t è s s o m a è s t r a 
n d ì s o n t a t i k i a t è r a t i n ì c h a p à r o n t a s t i n a g l i s ì a 
M a r ì k a e s ù è f e 
m b ì k e a p ò t t u 
è n a v o r à s o o s s o m ì k a m è r i 
ì c h a n a a g o r à s o o s s o m ì k a m è r i 
è n a v o r à s o o t s o m ì k u à i k u à i m è r i 
à r t e k a c ì n i e n è r k o t t e p l è o 
s p ì c c e t s a à t s e g r à t s i 
e m a r è s s a t o t a l à c h a n a 
o t ì c h o t è l i n a n g h i a l ì 
e t u s m è n u m e p l è o 
e n ì c h e t i k à m i 
s t e a n k ò r a m a r è o n t a 
u g e n i t ò r u e n è n u s a l l i m o n ì s o m e m a i 
e j i n è k a t è l i n a p u l i z z è s s i o s p i t i k u à i m è r i n a s t a s ì p u l i t a 
ì s t i g g h e a n k ò r a m a r è o n t a 
o a p e t a m m è n o i k l è e t e 
o à b b i t o u k o r a s ì u t è l i à s p r o 
e v ò e n ì m e a n k ò r a p r ò n t a n g h ì z i n a r t i s t e s e t t ò 
d ò p u o G i o v à n n i j ù r i s e è s s u 
j a t ì ì c h e p o l e m ì s o n t a p o d d h ì 
o t ì c h o t è l i è n a n j a l ì 
i p à s t a t è l i à l a 
k a n o n ò n t a t a s ì n n e f a n o ò k a v r è c h i 
f ò r s i s t è o n e a n k ò r a a t s ù n n i t i 
m i n d è l a à l l e s è t t e k a v ò e n ì m e p r ò n t a 
t i k à n n i e A n n a o s à m b a p o r n ò 
ì c h a n a v o r à s o o t s o m ì k u à i m è r i 
i t è l i k l a m m è n o 
e v ò e n e s s è r o t i e n a g r à s s o 
i A n n a à r t e n a s t è i i t t u m b r ò s e m è n a s t e p l ò n n i 
