evò sto derfò- mu en tu tò grazza mài ènan gràmma u derfù- mmu
o messère mu\' pe ka en è\' na fào glicèa ja mu kànnone dànno is emèna mu piacèone ce ta tròo
isoggèste ka mbìke apò ttu
ègratsa ènan gràmma u derfù- mmu
i màna ce o ciùri en è en è no scerrètsoma mài jatì ma dòkane i zoì ce agàpi
ìstigghe ankòra marèonta
ifènete ka o làdro mbìke apò ttu
ta kàjo travùdia igràfutte atsè nìtta
a\' telìsi na mìni pànta lettò mi fài to vrài
to spìti to fabbrikèone i fabbrikatòri
pào cerkèonta èna màkina ka kunsumèi olì benzìna
evò sti\' zoì- mmu ìme pànta polemimmèna
ettù mèsa tèli èna tappèto
o làdro imbìke apò ttu
ìrte grammèno
kanèna sto telèfono tèli na tsèri àttin Anna
to spìccetsa atsè kàmi
ìme ndimèni
evò en ìme grammèna mai an gràmma t aderfù- mmu
cìo ìssere ka sìmberi kànni ssìchra ce e\' tèlise na rti
nditònta
evò dòpo jurìzo vekkiarèdda pulò spìti- mu ka ècho Venèzia stin Venèzia ce èrkome na zìso ettù sti\' Kalimèro
en è\' na tus mìnome
ìse già famèna
èstasa
ettù ankòra stèon m\' o lìmo anammèno ce estèone assùnniti
i kiatèra- mu itèli na pài
en ìme ankòra endimèni
sto\' tìcho tèli o jalì
to fài ee tèli famèno sùbito è prèsto
ikàmato già ta làchana
tes marangiàne tèlune ee votimmène
pùru ka s\' ìta mia forà solamènte e\' s\' allimonò mài
